# vim: set ts=2 sw=2 tw=0 fo=cnqoj
version: 2

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - main: ./cmd/devd
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - formats: ["tar.gz"]
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    format_overrides:
      - goos: windows
        formats: ["zip"]

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"

homebrew_casks:
  - name: devd
    homepage: "https://github.com/llimllib/devd"
    description: " A local webserver for developers"
    license: "MIT"
    repository:
      owner: llimllib
      name: homebrew-tap
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    url:
      verified: "github.com/llimllib/devd"
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/devd"]
          end
