on: [push]
name: CI
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.19]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
    - uses: actions/checkout@v3
    - run: go test ./...
    - name: golangci-lint
      # https://github.com/golangci/golangci-lint-action has some options you can set
      # they recomnmend running it in a separate action, do so if it feels necessary
      uses: golangci/golangci-lint-action@v3
      with:
          version: latest
          # Optional: show only new issues if it's a pull request. The default value is `false`.
          # only-new-issues: true
          # Optional: if set to true then the all caching functionality will be complete disabled,
          #           takes precedence over all other caching options.
          # skip-cache: true
          # Optional: if set to true then the action don't cache or restore ~/go/pkg.
          # skip-pkg-cache: true
          # Optional: if set to true then the action don't cache or restore ~/.cache/go-build.
          # skip-build-cache: true
